version: '3.7'
services:
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=shop
      - MYSQL_PASSWORD=shoppass
      - MYSQL_DATABASE=db_shop
    volumes:
      - /var/lib/mysql
      #- "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3306:3306" # MariaDB Port
    networks:
      - db
  
  web:
    image: nginx:latest
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - php
    networks:
      - app

  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    links:
      - mariadb
      # - mail
      # - redis
    depends_on:
      - mariadb
    # environment:
    #   PHP_IDE_CONFIG: serverName=grafikart  # PHPstorm
    networks:
      - app
      - db

  node:
    build:
      context: ./docker/node
    command: yarn run build
    working_dir: /usr/src/app
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080

networks:
  db:
  app:
