#index:
#    path: /
#    controller: App\Controller\DefaultController::index
blog_list:
    path:      /blog/{page}
    controller: App\Controller\BlogController::list
    requirements:
        page: '\d+'

blog_show:
    # ...